import {
  BrainCircuit,
  BadgeCheck,
  FileSearch,
  TrendingUp,
  ShieldCheck,
  History,
} from "lucide-react";

import "./Features.css";

const features = [
  {
    icon: <BrainCircuit size={34} />,
    title: "AI Resume Analysis",
    description:
      "Receive detailed AI-powered feedback to improve your resume quality and increase interview opportunities.",
  },
  {
    icon: <BadgeCheck size={34} />,
    title: "ATS Score",
    description:
      "Measure how well your resume performs against modern Applicant Tracking Systems.",
  },
  {
    icon: <FileSearch size={34} />,
    title: "Resume Parsing",
    description:
      "Automatically extract resume details into a structured format within seconds.",
  },
  {
    icon: <TrendingUp size={34} />,
    title: "Improvement Suggestions",
    description:
      "Discover strengths, weaknesses, and actionable recommendations generated by AI.",
  },
  {
    icon: <ShieldCheck size={34} />,
    title: "Secure Storage",
    description:
      "Your resumes and analysis reports are securely stored and accessible anytime.",
  },
  {
    icon: <History size={34} />,
    title: "Analysis History",
    description:
      "Track previous resume analyses and compare improvements over time.",
  },
];

const Features = () => {
  return (
    <section className="features section">
      <div className="container">

        <div className="section-heading">

          <span>FEATURES</span>

          <h2>
            Everything You Need To Build
            A Better Resume
          </h2>

          <p>
            Powerful AI tools designed to help job seekers
            improve resumes, increase ATS compatibility,
            and land more interviews.
          </p>

        </div>

        <div className="features-grid">

          {features.map((feature, index) => (
            <div
              className="feature-card"
              key={index}
            >
              <div className="feature-icon">
                {feature.icon}
              </div>

              <h3>{feature.title}</h3>

              <p>{feature.description}</p>
            </div>
          ))}

        </div>

      </div>
    </section>
  );
};

export default Features;